### 上传文件
POST {{media_host}}/media/upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="hh.pdf"
Content-Type: application/octet-stream

< C:\Users\汪思敏\Downloads\hh.pdf
